<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\OrdersProducts;
use Illuminate\Support\Facades\DB;

class OrdersProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        OrdersProducts::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        OrdersProducts::insert([
            [
                'productsId' => 3549,
                'ordersId' => 2,
                'unitPrice' => '2.36',
                'totalPrice' => '2.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 830,
                'ordersId' => 2,
                'unitPrice' => '3.67',
                'totalPrice' => '4.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 991,
                'ordersId' => 2,
                'unitPrice' => '3.67',
                'totalPrice' => '58.65',
                'quantity' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1211,
                'ordersId' => 2,
                'unitPrice' => '23',
                'totalPrice' => '45',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1212,
                'ordersId' => 2,
                'unitPrice' => '34',
                'totalPrice' => '56',
                'quantity' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 6912,
                'ordersId' => 2,
                'unitPrice' => '32',
                'totalPrice' => '56',
                'quantity' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 5014,
                'ordersId' => 2,
                'unitPrice' => '45',
                'totalPrice' => '54',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 3549,
                'ordersId' => 3,
                'unitPrice' => '2.36',
                'totalPrice' => '2.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 830,
                'ordersId' => 3,
                'unitPrice' => '3.67',
                'totalPrice' => '4.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 991,
                'ordersId' => 3,
                'unitPrice' => '3.67',
                'totalPrice' => '58.65',
                'quantity' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1211,
                'ordersId' => 3,
                'unitPrice' => '23',
                'totalPrice' => '45',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1212,
                'ordersId' => 3,
                'unitPrice' => '34',
                'totalPrice' => '56',
                'quantity' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 6912,
                'ordersId' => 3,
                'unitPrice' => '32',
                'totalPrice' => '56',
                'quantity' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 5014,
                'ordersId' => 3,
                'unitPrice' => '45',
                'totalPrice' => '54',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1,
                'ordersId' => 6,
                'unitPrice' => '2.36',
                'totalPrice' => '2.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 2,
                'ordersId' => 6,
                'unitPrice' => '3.67',
                'totalPrice' => '4.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 4,
                'ordersId' => 6,
                'unitPrice' => '3.67',
                'totalPrice' => '58.65',
                'quantity' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 5,
                'ordersId' => 6,
                'unitPrice' => '23',
                'totalPrice' => '45',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 6,
                'ordersId' => 6,
                'unitPrice' => '34',
                'totalPrice' => '56',
                'quantity' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 7,
                'ordersId' => 6,
                'unitPrice' => '32',
                'totalPrice' => '56',
                'quantity' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 18,
                'ordersId' => 6,
                'unitPrice' => '45',
                'totalPrice' => '54',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 3549,
                'ordersId' => 6,
                'unitPrice' => '2.36',
                'totalPrice' => '2.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 830,
                'ordersId' => 6,
                'unitPrice' => '3.67',
                'totalPrice' => '4.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 991,
                'ordersId' => 6,
                'unitPrice' => '3.67',
                'totalPrice' => '58.65',
                'quantity' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1211,
                'ordersId' => 6,
                'unitPrice' => '23',
                'totalPrice' => '45',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1212,
                'ordersId' => 6,
                'unitPrice' => '34',
                'totalPrice' => '56',
                'quantity' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 6912,
                'ordersId' => 6,
                'unitPrice' => '32',
                'totalPrice' => '56',
                'quantity' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 5014,
                'ordersId' => 6,
                'unitPrice' => '45',
                'totalPrice' => '54',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1,
                'ordersId' => 10,
                'unitPrice' => '2.36',
                'totalPrice' => '2.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 2,
                'ordersId' => 10,
                'unitPrice' => '3.67',
                'totalPrice' => '4.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 4,
                'ordersId' => 10,
                'unitPrice' => '3.67',
                'totalPrice' => '58.65',
                'quantity' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 5,
                'ordersId' => 10,
                'unitPrice' => '23',
                'totalPrice' => '45',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 6,
                'ordersId' => 10,
                'unitPrice' => '34',
                'totalPrice' => '56',
                'quantity' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 7,
                'ordersId' => 10,
                'unitPrice' => '32',
                'totalPrice' => '56',
                'quantity' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 18,
                'ordersId' => 10,
                'unitPrice' => '45',
                'totalPrice' => '54',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 3549,
                'ordersId' => 10,
                'unitPrice' => '2.36',
                'totalPrice' => '2.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 830,
                'ordersId' => 10,
                'unitPrice' => '3.67',
                'totalPrice' => '4.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 991,
                'ordersId' => 10,
                'unitPrice' => '3.67',
                'totalPrice' => '58.65',
                'quantity' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1211,
                'ordersId' => 10,
                'unitPrice' => '23',
                'totalPrice' => '45',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1212,
                'ordersId' => 10,
                'unitPrice' => '34',
                'totalPrice' => '56',
                'quantity' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 6912,
                'ordersId' => 10,
                'unitPrice' => '32',
                'totalPrice' => '56',
                'quantity' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 5014,
                'ordersId' => 10,
                'unitPrice' => '45',
                'totalPrice' => '54',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1,
                'ordersId' => 1,
                'unitPrice' => '2.36',
                'totalPrice' => '2.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 2,
                'ordersId' => 1,
                'unitPrice' => '3.67',
                'totalPrice' => '4.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 4,
                'ordersId' => 1,
                'unitPrice' => '3.67',
                'totalPrice' => '58.65',
                'quantity' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 5,
                'ordersId' => 1,
                'unitPrice' => '23',
                'totalPrice' => '45',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 6,
                'ordersId' => 1,
                'unitPrice' => '34',
                'totalPrice' => '56',
                'quantity' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 7,
                'ordersId' => 1,
                'unitPrice' => '32',
                'totalPrice' => '56',
                'quantity' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 18,
                'ordersId' => 1,
                'unitPrice' => '45',
                'totalPrice' => '54',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 3549,
                'ordersId' => 1,
                'unitPrice' => '2.36',
                'totalPrice' => '2.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 830,
                'ordersId' => 1,
                'unitPrice' => '3.67',
                'totalPrice' => '4.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 991,
                'ordersId' => 1,
                'unitPrice' => '3.67',
                'totalPrice' => '58.65',
                'quantity' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1211,
                'ordersId' => 1,
                'unitPrice' => '23',
                'totalPrice' => '45',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1212,
                'ordersId' => 1,
                'unitPrice' => '34',
                'totalPrice' => '56',
                'quantity' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 6912,
                'ordersId' => 1,
                'unitPrice' => '32',
                'totalPrice' => '56',
                'quantity' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 5014,
                'ordersId' => 1,
                'unitPrice' => '45',
                'totalPrice' => '54',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1,
                'ordersId' => 4,
                'unitPrice' => '2.36',
                'totalPrice' => '2.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 2,
                'ordersId' => 4,
                'unitPrice' => '3.67',
                'totalPrice' => '4.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 4,
                'ordersId' => 4,
                'unitPrice' => '3.67',
                'totalPrice' => '58.65',
                'quantity' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 5,
                'ordersId' => 4,
                'unitPrice' => '23',
                'totalPrice' => '45',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 6,
                'ordersId' => 4,
                'unitPrice' => '34',
                'totalPrice' => '56',
                'quantity' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 7,
                'ordersId' => 5,
                'unitPrice' => '32',
                'totalPrice' => '56',
                'quantity' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 18,
                'ordersId' => 5,
                'unitPrice' => '45',
                'totalPrice' => '54',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 3549,
                'ordersId' => 7,
                'unitPrice' => '2.36',
                'totalPrice' => '2.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 830,
                'ordersId' => 7,
                'unitPrice' => '3.67',
                'totalPrice' => '4.56',
                'quantity' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 991,
                'ordersId' => 8,
                'unitPrice' => '3.67',
                'totalPrice' => '58.65',
                'quantity' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1211,
                'ordersId' => 9,
                'unitPrice' => '23',
                'totalPrice' => '45',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 1212,
                'ordersId' => 9,
                'unitPrice' => '34',
                'totalPrice' => '56',
                'quantity' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 6912,
                'ordersId' => 9,
                'unitPrice' => '32',
                'totalPrice' => '56',
                'quantity' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productsId' => 5014,
                'ordersId' => 9,
                'unitPrice' => '45',
                'totalPrice' => '54',
                'quantity' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}